/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2018-09-24 13:47:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>FINBOT</title>\r\n");
      out.write("  <link rel=\"icon\" href=\"image/favicon2.ico\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"d-flex flex-column flex-md-row align-items-center\r\n");
      out.write("  p-3 px-md-4 mb-3 bg-light border-bottom shadow-sm fixed-top containerMenu\" id=\"menu\">\r\n");
      out.write("  <h5 class=\"my-0 mr-md-auto font-weight-normal tituloMenu\">FINBOT</h5>\r\n");
      out.write("  <nav class=\"my-2 my-md-0 mr-md-3\">\r\n");
      out.write("    <a class=\"p-2  linkMenus\" href=\"#inicio\">INICIO</a>\r\n");
      out.write("    <a class=\"p-2  linkMenus\" href=\"#sobre\">SOBRE NOS</a>\r\n");
      out.write("    <a class=\"p-2  linkMenus\" href=\"#sugestÃµes\">SUGESTOES</a>\r\n");
      out.write("    <a class=\"p-2  linkMenus\" href=\"#identidade\">NOSSA IDENTIDADE</a>\r\n");
      out.write("    <a class=\"p-2  linkMenus\" href=\"#chatBot\">CHATBOT</a>\r\n");
      out.write("    <a class=\"p-2  linkMenus\" href=\"#equipe\">EQUIPE</a>\r\n");
      out.write("    <a class=\"p-2  linkMenus\" href=\"#contato\">CONTATO</a>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <a class=\"btn botaoMenu\" href=\"login.jsp\">LOGIN</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"tipoContainer parallax2\" id=\"inicio\">\r\n");
      out.write("  <div class=\"qualquer\">\r\n");
      out.write("    <div id=\"fundo\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-12\">\r\n");
      out.write("            <h1 class=\"nomeEmpresa\">FINBOT</h1>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-12\">\r\n");
      out.write("            <p class=\"slogan\">Seus sonhos, metas e desejos sÃ£o a nossa prioridade!!!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"primeiroContainer\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-md-4 logo\">\r\n");
      out.write("        <!-- <img class=\"logo img-responsive\" src=\"image/finbot-logo1.png\" alt=\"\"> -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-8\" id=\"primeirotexto\">\r\n");
      out.write("        <h1 class=\"subtitulo\">FINBOT</h1>\r\n");
      out.write("        <p class=\"texto centro\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Um bate-papo com o Finbot pode ser a porta de entrada para investimentos e um adeus Ã¡s dÃ­vidas.</p>\r\n");
      out.write("        <p class=\"texto\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nosso projeto busca ajudar os jovens a resolver seus problemas financeiros e alcanÃ§ar seus sonhos e metas de forma sustentÃ¡vel. Com o desenvolvimento de uma plataforma de educaÃ§Ã£o financeira integrada com um chatbot responsÃ¡vel por tirar dÃºvidas de usuÃ¡rios.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"tipoContainer2 parallax3\" id=\"sobre\">\r\n");
      out.write("  <div class=\"qualquer\">\r\n");
      out.write("    <div id=\"fundo\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-12\">\r\n");
      out.write("            <h1 class=\"titulo\">Sobre nÃ³s</h1>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-12\">\r\n");
      out.write("            <p id=\"subtituloParalax\">Conheca um pouco sobre nosso projeto com uma apresentacÃ£o sobre o chatBot,metas e Boa GestÃ£o!!!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"py-5 fundo2\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <div class=\"card fundo2\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <img class=\"card-img-top primeirasImagens\" src=\"image/ChatBot.png\" alt=\"Card image cap\">\r\n");
      out.write("            <h3 class=\"card-title subtituloInicio\">ChatBot</h3>\r\n");
      out.write("            <p class=\"card-text textoConteudo\">O chatbot se comunica com o usuÃ¡rio, perguntando suas metas e objetivo , a partir do informado pelo usuÃ¡rio o sistema analisa a viabilidade do objetivo informado e oferece uma sÃ©rie de sugestÃµes com o tempo e o custo necessÃ¡rio.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <div class=\"card fundo2\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <img class=\"card-img-top primeirasImagens\" src=\"image/imagemQualquer.png\" alt=\"Card image cap\">\r\n");
      out.write("            <h3 class=\"card-title subtituloInicio\">GestÃ£o</h3>\r\n");
      out.write("            <p class=\"card-text textoConteudo\">Equilibrar gastos com as necessidades e desejos Ã© uma prÃ¡tica saudÃ¡vel. VocÃª compromete o salÃ¡rio antes de receber, nÃ£o dÃ¡ preferÃªncia para comprar Ã  vista, consome mais do que ganha e nÃ£o planeja para possiveis complicaÃ§Ãµes?</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <div class=\"card fundo2\">\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <img class=\"card-img-top primeirasImagens\" alt=\"Card image cap\" src=\"image/meta.png\">\r\n");
      out.write("            <h3 class=\"card-title subtituloInicio\">Metas</h3>\r\n");
      out.write("            <p class=\"card-text textoConteudo\">Nossa meta Ã© ajudar vocÃª conquistar seus objetivos, realizar investimentos de forma facil e segura, o uso consciente dos cartÃµes, contribuir uma poupanÃ§a e a economizae para comprar um carro ou realizar a viagem dos sonhos.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"tipoContainer2 parallax4\" id=\"sugestÃµes\">\r\n");
      out.write("  <div class=\"qualquer\">\r\n");
      out.write("    <div id=\"fundo\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-12\">\r\n");
      out.write("            <h1 class=\"titulo2\">SugestÃµes e Video</h1>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-12\">\r\n");
      out.write("            <p id=\"subtituloParalax3\">Conheca um pouco sobre nosso projeto com uma apresentacÃ£o sobre o chatBot,metas e Boa GestÃ£o!!!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <h1 class=\"subtituloSugestao\">SugestÃµes</h1>\r\n");
      out.write("  <div class=\"row rowSugestao\">\r\n");
      out.write("    <div class=\"col-md-4 \">\r\n");
      out.write("      <div class=\"container bordaSugestao\">\r\n");
      out.write("        <h2 class=\"tituloSugestoes\">EducaÃ§Ã£o Financeira</h2>\r\n");
      out.write("        <p class=\"textoSugestoes\">O nosso objetivo Ã© transmitir informaÃ§Ãµes sobre educaÃ§Ã£o financeira e conhecimento de como manter o seu entendimento deste mercado, ensinando ao usuÃ¡rio alguns conceitos como despesas Ãºteis, inÃºteis e como obter crÃ©dito e pontuaÃ§Ã£o.</p>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-md botaoSugestao\" data-toggle=\"modal\" data-target=\"#Modal2\">Leia mais...</button>\r\n");
      out.write("        <div class=\"modal fade\" id=\"Modal2\" role=\"dialog\">\r\n");
      out.write("          <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("              <div class=\"modal-header\">\r\n");
      out.write("                <h4 class=\"modal-title tituloModal\">EducaÃ§Ã£o Financeira</h4>\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"modal-body\">\r\n");
      out.write("                <p  class=\"textoModal\">O nosso objetivo Ã© transmitir informaÃ§Ãµes sobre educaÃ§Ã£o financeira e conhecimento como manter o seu entendimento deste mercado financeiro. </p>\r\n");
      out.write("                <p  class=\"textoModal\">Vamos entÃ£o comeÃ§ar entender alguns conceitos como despesas e crÃ©dito</p>\r\n");
      out.write("                <h2 class=\"tituloTextoModal\">Rendimentos(Renda)</h2>\r\n");
      out.write("                <p  class=\"textoModal\">Quantia recebida regularmente como resultado de investimentos, aluguel de imÃ³veis , ou quantia recebida regularmente por trabalho realizado o(SalÃ¡rio) etc.</p>\r\n");
      out.write("                <h2 class=\"tituloTextoModal\">Despesas</h2>\r\n");
      out.write("                <p  class=\"textoModal\">Despesas\r\n");
      out.write("                  As despesas estÃ£o relacionadas com os gastos usados para a sua manutenÃ§Ã£o e sobrevivÃªncia. SÃ£o entendidos os gastos com aluguel,Ã¡gua,luz telefone, supermercado, carro entre outros. </p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">CrÃ©dito</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">CrÃ©dito Ã© a cessÃ£o de mercadoria, serviÃ§o ou dinheiro para pagamento futuro. Sempre que compramos a crÃ©dito pagamos um valor adicional pelo tempo que levaremos para quitar a dÃ­vida. Esse valor Ã© o que chamamos de juro. </p>\r\n");
      out.write("                  <p  class=\"textoModal\">O consumo faz parte de nosso cotidiano. A todo momento consumimos alguma coisa, mas a diferenÃ§a esta em identificar qual tipo de consumidor somos: </p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">Consumidores conscientes </h2>\r\n");
      out.write("                  <p  class=\"textoModal\">aproveitam as oportunidades para consumir ou adquirir aquilo que Ã© necessÃ¡rio Ã  sua sobrevivÃªncia e bem estar,sempre considerando suas reais possibilidades financeiras, bem como as conseqÃ¼Ãªncias que os seus atos irÃ£o causar ao meio ambiente e Ã  sociedade. </p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">Consumistas</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">Escravo dos seus desejos. Segue seus impulsos e nÃ£o pensa nas conseqÃ¼Ãªncias de seus atos. O prazer estÃ¡ no ato da compra. RefÃ©m de seus impulsos, nunca atinge a satisfaÃ§Ã£o plena, pois, apÃ³s uma compra, sua meta serÃ¡ outra. </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-default botaoModal\" data-dismiss=\"modal\">Sair</button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-4 \">\r\n");
      out.write("        <div class=\"container bordaSugestao\">\r\n");
      out.write("          <h2 class=\"tituloSugestoes\">Investimento para jovens</h2>\r\n");
      out.write("          <p class=\"textoSugestoes\">Iniciar seus investimentos jovem Ã© uma grande vantagem para quem busca tranquilidade financeira: as aplicaÃ§Ãµes de longo prazo, alÃ©m de mais seguras, costumam oferecer rendimentos maiores, aumentando os lucros.</p>\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-md botaoSugestao\" data-toggle=\"modal\" data-target=\"#Modal5\">Leia mais...</button>            <!-- Modal -->\r\n");
      out.write("          <div class=\"modal fade\" id=\"Modal5\" role=\"dialog\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("              <!-- Modal content-->\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                  <h4 class=\"modal-title tituloModal\">Investimento para jovens</h4>\r\n");
      out.write("                  <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">Investimentos para jovens: um bom negÃ³cio?</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">Essa mudanÃ§a no perfil e faixa etÃ¡ria dos investidores Ã©, na verdade, uma grande vantagem para quem busca tranquilidade financeira: as aplicaÃ§Ãµes de longo prazo, alÃ©m de mais seguras, costumam oferecer rendimentos maiores, aumentando os lucros de quem investe na hora certa.</p>\r\n");
      out.write("                  <p  class=\"textoModal\">Por isso, os investimentos para jovens estÃ£o em constante ascensÃ£o, sendo cada vez mais procurados por estudantes, recÃ©m-formados e profissionais adentrando no mercado de trabalho.</p>\r\n");
      out.write("                  <p  class=\"textoModal\">E se engana quem pensa que Ã© necessÃ¡rio contar com um montante inicial alto para comeÃ§ar a investir. Muitas opÃ§Ãµes nÃ£o exigem altas somas, e podem contribuir com a meta de valorizar o capital com o passar do tempo, com risco moderado ou baixo.</p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">O que saber antes de comeÃ§ar a investir?</h2>\r\n");
      out.write("                  <p  class=\"textoModal\"> class=\"tituloTextoModal\"Se vocÃª pretende reservar uma parte dos seus rendimentos para investir, Ã© importante estar atento para alguns cuidados importantes antes de comeÃ§ar:</p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">Todo investimento tem custos</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">Taxas de administraÃ§Ã£o, de performance, de custÃ³dia, de liquidaÃ§Ã£o, impostos e taxa sobre movimentaÃ§Ã£o sÃ£o encargos que podem recair sobre as aplicaÃ§Ãµes, e devem ser contabilizados antes de escolher por determinada instituiÃ§Ã£o ou investimento.</p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">Os impostos podem reduzir a rentabilidade</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">Com poucas exceÃ§Ãµes (como a poupanÃ§a), os investimentos sÃ£o taxados em diferentes tipos de impostos, desde o conhecido Imposto de Renda atÃ© o Imposto sobre OperaÃ§Ãµes Financeiras (IOF). Esses valores devem ser analisados para evitar surpresas desagradÃ¡veis na hora de liquidar as aplicaÃ§Ãµes.</p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">Conhecer o mercado Ã© fundamental</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">NÃ£o importa se vocÃª Ã© iniciante ou um investidor experiente, sempre hÃ¡ o que aprender. Acompanhar o cenÃ¡rio econÃ´mico e o desempenho dos principais investimentos pode fazer a diferenÃ§a em sua performance nos negÃ³cios.</p>\r\n");
      out.write("                  <p  class=\"textoModal\">A maior vantagem em comeÃ§ar cedo no mundo dos investimentos Ã© a possibilidade de se recuperar rapidamente de eventuais prejuÃ­zos ou aplicaÃ§Ãµes mal sucedidas. Isso garante mais liberdade para investir, mas como em qualquer idade, Ã© recomendado diversificar os tipos de investimento, em busca da maior rentabilidade possÃ­vel no futuro.</p>\r\n");
      out.write("                  <p  class=\"textoModal\">Dessa forma, uma boa estratÃ©gia seria mesclar as aplicaÃ§Ãµes, destinando a maior parte do dinheiro em opÃ§Ãµes mais conservadoras e com prazo mais curto de retorno, para garantir as despesas de mÃ©dio prazo (como os estudos, a compra de um carro ou imÃ³vel ou o casamento).</p>\r\n");
      out.write("                  <p  class=\"textoModal\">Uma porcentagem menor pode ser reservada para aplicaÃ§Ãµes mais arriscadas e de longo prazo, com retornos mais altos, destinadas Ã  aposentadoria, por exemplo.</p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">Quais sÃ£o os melhores investimentos para jovens disponÃ­veis no mercado?</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">Nesse contexto, algumas opÃ§Ãµes de investimentos para jovens que podem entrar em sua carteira de aplicaÃ§Ãµes sÃ£o:</p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">Certificado de DepÃ³sito BancÃ¡rio (CDB)</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">O CDB nada mais Ã© que um tÃ­tulo emitido pelos bancos que tem por objetivo levantar capital para financiar atividades de crÃ©dito â ou seja, o investidor recebe rentabilidade diÃ¡ria por um tipo de emprÃ©stimo Ã  instituiÃ§Ã£o financeira. Existem trÃªs tipos de certificados:</p>\r\n");
      out.write("                  <p  class=\"textoModal\">- no CDB prÃ©-fixado, os juros sÃ£o negociados no momento do investimento; - no CDB pÃ³s-fixado, os juros sÃ£o baseados em taxas de referÃªncia, normalmente a taxa Selic; - na terceira modalidade, os juros acompanham a inflaÃ§Ã£o.</p>\r\n");
      out.write("                  <p  class=\"textoModal\">Considerado como um investimento de baixo risco, ele ainda oferece a vantagem de incidÃªncia regressiva do imposto de renda: quanto maior o tempo de aplicaÃ§Ã£o, menor a tarifaÃ§Ã£o cobrada no resgate. O valor mÃ­nimo para investir no CDB gira em torno de 500 reais.</p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">Fundos de Investimento</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">Uma opÃ§Ã£o que se destaca entre os investimentos para jovens, essa aplicaÃ§Ã£o oferece Ã³tima rentabilidade em longo prazo, e por isso pode ser uma boa escolha para a realizaÃ§Ã£o de um sonho de consumo, por exemplo. </p>\r\n");
      out.write("                  <p  class=\"textoModal\">AlÃ©m disso, as melhores aplicaÃ§Ãµes sÃ£o escolhidas a dedo pelo banco ou instituiÃ§Ã£o financeira contratada, tirando do investidor a responsabilidade de investigar as diversas opÃ§Ãµes disponÃ­veis no mercado na hora de decidir para onde vai seu dinheiro.</p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">PoupanÃ§a</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">Ainda que nÃ£o seja considerada por economistas como um investimento, a poupanÃ§a continua sendo uma das aplicaÃ§Ãµes mais utilizadas pelos brasileiros para poupar dinheiro, tanto em curto quanto mÃ©dio e longo prazo.</p>\r\n");
      out.write("                  <p  class=\"textoModal\">Apesar da baixa rentabilidade (abaixo de praticamente todos os outros tipos de investimento), a poupanÃ§a oferece isenÃ§Ã£o da incidÃªncia de taxas, inclusive o imposto de renda, e alta liquidez â o dinheiro pode ser resgatado a qualquer momento.</p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">PrevidÃªncia Privada</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">Os tÃ­tulos de previdÃªncia privada sÃ£o considerados investimentos de longo prazo, e demandam contribuiÃ§Ãµes mensais do investidor, a fim de acumular uma reserva que pode ser utilizada para a aposentadoria, por exemplo.</p>\r\n");
      out.write("                  <p  class=\"textoModal\">O regime de tributaÃ§Ã£o tambÃ©m depende do prazo escolhido para o resgate da aplicaÃ§Ã£o, que pode ser recebida de uma sÃ³ vez ou na forma de depÃ³sitos mensais.</p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">Letras de CrÃ©dito</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">Do tipo imobiliÃ¡rio ou agronegÃ³cio, esses tÃ­tulos tÃªm por objetivo financiar emprÃ©stimos nos respectivos setores, e oferecem baixo risco e boa rentabilidade.</p>\r\n");
      out.write("                  <p  class=\"textoModal\">Por isso, sÃ£o considerados bons investimentos para jovens. AlÃ©m disso, sÃ£o isentos de tributaÃ§Ã£o de imposto de renda para pessoas fÃ­sicas.</p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">Tesouro Direto</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">Esse investimento se baseia em tÃ­tulos pÃºblicos oferecidos pelo Governo Federal que possuem rendimentos prefixados jÃ¡ no momento da compra, variando de acordo com o prazo para seu resgate. Esses tÃ­tulos financiam diversas aÃ§Ãµes federais nas Ã¡reas de educaÃ§Ã£o, saÃºde e vÃ¡rias outras.</p>\r\n");
      out.write("                  <p  class=\"textoModal\">Por serem tÃ­tulos pÃºblicos, sÃ£o considerados investimentos seguros e de risco baixo. Com valores a partir de 30 reais jÃ¡ Ã© possÃ­vel investir no Tesouro Direto, mas essa opÃ§Ã£o tem a desvantagem de sÃ³ oferecer rentabilidade no prazo estipulado para o resgate.</p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">ConsÃ³rcios</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">Simples, seguro e acessÃ­vel, o consÃ³rcio Ã© um dos melhores investimentos para jovens, jÃ¡ que oferece inÃºmeras vantagens em comparaÃ§Ã£o com outros tipos de aplicaÃ§Ãµes: com parcelas fixas e sem juros, Ã© possÃ­vel adquirir bens como carros ou imÃ³veis sem excesso de burocracia e contando com parcelamentos que nÃ£o comprometem o orÃ§amento.</p>\r\n");
      out.write("                  <p  class=\"textoModal\">AlÃ©m disso, nÃ£o Ã© necessÃ¡rio contar apenas com a sorte para ser contemplado â Ã© possÃ­vel dar um lance e receber a carta de crÃ©dito mais rÃ¡pido caso seja o vencedor. Dessa forma, basta um planejamento eficiente para manter as parcelas do consÃ³rcio em dia e reservar uma parte dos rendimentos mensais para oferecer um lance maior que o normal.</p>\r\n");
      out.write("                  <p  class=\"textoModal\">NÃ£o faltam no mercado opÃ§Ãµes vantajosas de investimentos para jovens, com rentabilidade e capital inicial variÃ¡veis. Por isso, mesmo sem muitos recursos para investir, Ã© importante comeÃ§ar cedo para utilizar o fator tempo como aliado.</p>\r\n");
      out.write("                  <p  class=\"textoModal\">AplicaÃ§Ãµes de mÃ©dio e longo prazo podem equilibrar eventuais perdas e gerar lucros reais para o investidor, contribuindo para sua estabilidade financeira e conquista de seu patrimÃ´nio.</p>\r\n");
      out.write("                  <p  class=\"textoModal\">De fato, essas sÃ£o prÃ¡ticas que nos dÃ£o uma visÃ£o aprimorada acerca da natureza de nossas receitas e de nossos gastos e possibilitam a identificaÃ§Ã£o de atitudes que afetam negativamente a saÃºde de nossas finanÃ§as.</p>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-default botaoModal\" data-dismiss=\"modal\">Sair</button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-md-4 \">\r\n");
      out.write("        <div class=\"container bordaSugestao\">\r\n");
      out.write("          <h2 class=\"tituloSugestoes\">Seu nome esta sujo?</h2>\r\n");
      out.write("          <p class=\"textoSugestoes\">Apesar de muitas tentativas e negociaÃ§Ãµes, muitas vezes os problemas sÃ£o maiores e nÃ£o conseguimos sanar as nossas dÃ­vidas, entÃ£o comeÃ§am os protestos, o nosso nome estÃ¡ nos Ã³rgÃ£o de proteÃ§Ã£o ao crÃ©dito. Como agir para limpar seu nome?</p>\r\n");
      out.write("          <!-- Trigger the modal with a button -->\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-md botaoSugestao\" data-toggle=\"modal\" data-target=\"#Modal6\">Leia mais...</button>\r\n");
      out.write("\r\n");
      out.write("          <!-- Modal -->\r\n");
      out.write("          <div class=\"modal fade\" id=\"Modal6\" role=\"dialog\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("              <!-- Modal content-->\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header tituloModal\">\r\n");
      out.write("                  <h4 class=\"modal-title\">Seu nome esta sujo?</h4>\r\n");
      out.write("                  <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                  <p  class=\"textoModal\">Apesar de muitas tentativas e negociaÃ§Ãµes, muitas vezes os problemas sÃ£o maiores e nÃ£o conseguimos sanar as nossas dividas,e comeÃ§am os protestos,devoluÃ§Ãµes de cheques,o nosso nome Ã© incluÃ­do nos Ã³rgÃ£o de proteÃ§Ã£o ao crÃ©dito . </p>\r\n");
      out.write("                  <p  class=\"textoModal\">Mas como agir e procurar os Ã³rgÃ£os para limpar nosso nome necessidade de contratar uma empresa . </p>\r\n");
      out.write("                  <p  class=\"textoModal\">Entre em contato com a empresa para a qual vocÃª estÃ¡ devendo, fale com a Ã¡rea de cobranÃ§a e regularize sua dÃ­vida.</p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">TÃ­tulos Protestados</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">Se esta empresa o protestou ,pague sua divida e peÃ§a o instrumento de protesto ou carta de anuÃªncias e encaminhei aos Ã³rgÃ£os de proteÃ§Ã£o ao credito como Serasa/SPC para limpar seu nome de forma rÃ¡pida , alÃ©m de eefetuar e cancelamento do protesto perante o Tabelionato</p>\r\n");
      out.write("                  <p  class=\"textoModal\">Os nomes protestados ficam negativados (constando) nas instituiÃ§Ãµes de credito : Serasa,SPC,etc..., pelo prazo de permanencia de 5 anos </p>\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">Cheques s/Fundos</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">Ocorre quando cheque for devolvido duas vezes por falta de fundos ApÃ³s a recuperaÃ§Ã£o do cheque vÃ¡ ao banco e peÃ§a para o Banco excluir seu nome do(CCF) Cadastro de Emitentes de Cheques sem Fundos geralmente os bancos cobram uma taxa, No prazo mÃ¡ximo de cinco dias Ãºteis, contados da data da entrega do pedido do cliente, o banco deve efetuar a exclusÃ£o. </p>\r\n");
      out.write("\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">AÃ§Ã£o judicial</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">Ã o direito que tÃªm as pessoas fÃ­sicas e jurÃ­dicas de pedir em juÃ­zo o que lhes pertence ou Ã© devido. O termo ainda se refere ao documento (processo) que foi dada entrada em juÃ­zo (no fÃ³rum).Certifique-se de que o processo jÃ¡ foi julgado e se encontra arquivado ou extinto, por meio de cÃ³pia do despacho do juiz ou de certidÃ£o emitida pela Vara CÃ­vel onde o processo foi distribuÃ­do.De posse da comprovaÃ§Ã£o da existÃªncia de embargo Ã  execuÃ§Ã£o, penhora ou extinÃ§Ã£o do processo, entregue-a na Serasa/SPC </p>\r\n");
      out.write("\r\n");
      out.write("                  <h2 class=\"tituloTextoModal\">AÃ§Ã£o ou execuÃ§Ã£o federal</h2>\r\n");
      out.write("                  <p  class=\"textoModal\">Ocorre quando o cidadÃ£o deixa de pagar impostos, taxas ou contribuiÃ§Ãµes federais, esta anotaÃ§Ã£o tambÃ©m irÃ¡ constar no banco de dados dos Ã³rgÃ£os de proteÃ§Ã£o ao crÃ©dito.Apresente a certidÃ£o negativa de dÃ©bito da JustiÃ§a Federal, ou entregue um documento que comprove, relativamente Ã  dÃ­vida, o respectivo pagamento, acordo ou discussÃ£o judicial. Ao negociar ou quitar uma dÃ­vida, exija um documento que comprove o acordo. Isto basta para a retirada do nome de listas negativas, independente da dÃ­vida ter sido totalmente paga. A prÃ³pria empresa se encarrega de limpar o nome. </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-default botaoModal\" data-dismiss=\"modal\">Sair</button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"fundoVideo\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <h1 class=\"subtitulo\">Videos</h1>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-6 tudoVideo\">\r\n");
      out.write("          <!-- <iframe class=\"Video\"width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/covxjhXsCi8\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe> -->\r\n");
      out.write("          <iframe class=\"Video\" width=\"789\" height=\"444\" src=\"https://www.youtube.com/embed/B6CIQ_x4UnU\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <p class=\"tituloVideo\">Titulo Video</p>\r\n");
      out.write("          <p class=\"textoVideo\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <br><br>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <p class=\"tituloVideo\">Titulo Video</p>\r\n");
      out.write("          <p class=\"textoVideo\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6 tudoVideo\">\r\n");
      out.write("          <iframe  class=\"Video\"  width=\"789\" height=\"444\" src=\"https://www.youtube.com/embed/WYysK9-566k\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe>\r\n");
      out.write("          <!-- <iframe class=\"Video\" width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/0JHuHxwhKmc\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen></iframe> -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>    <br><br></div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"py-5\" id=\"identidade\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-12\">\r\n");
      out.write("            <h1 class=\"subtitulo\">Nossa Identidade</h1>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card \">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <img class=\"card-img-top sobremvs\" src=\"image/missao.png\" alt=\"Card image cap\">\r\n");
      out.write("                <h3 class=\"card-title subtituloMVC\">MissÃ£o</h3>\r\n");
      out.write("                <p class=\"card-text textoConteudo\">Nossa missÃ£o Ã© educar os jovens de maneira fÃ¡cil e didÃ¡tica a lidar com suas finanÃ§as de forma responsÃ¡vel, permitindo que eles aprendam a resolver seus problemas e dÃªem os primeiros passos no sentido de alcanÃ§ar seus objetivos.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <img class=\"card-img-top sobremvs\" src=\"image/visao.png\" alt=\"Card image cap\">\r\n");
      out.write("                <h3 class=\"card-title subtituloMVC\">VisÃ£o</h3>\r\n");
      out.write("                <p class=\"card-text textoConteudo\">Ser a escolha natural dos jovens em software para auxÃ­lio em sua vida finanÃ§as, expandir a idade de usuarios podendo auxiliar na vida financeira com grandes investimentos e expandir as nossas fronteiras</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <img class=\"card-img-top sobremvs\" alt=\"Card image cap\" src=\"image/valores.png\">\r\n");
      out.write("                <h3 class=\"card-title subtituloMVC\">Valores</h3>\r\n");
      out.write("                <p class=\"card-text textoConteudo\">Respeito com nossos usuÃ¡rios. Integridade com os dados do usuario. Garantir que nosso suporte e o chatBot consiga resolver seus conflitos. Garantia de uma melhora com relaÃ§Ã£o sua vida financeira.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"tipoContainer fundo3\" id=\"chatBot\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-md-7\" id=\"primeirotexto\">\r\n");
      out.write("            <h1 class=\"subtitulo\">Fale com o ChatBot</h1>\r\n");
      out.write("            <p class=\"texto centro\">FaÃ§a o cadastro para obter o Login e comece jÃ¡ a tirar suas dÃºvidas com o Finbot, organize sua vida financeira com uma conversa simples e informal, aprenda sobre juros abusivos, maneiras de controlar gastos, economia domestica, investimentos, cdb, cdi, metas e como se organizar para alcanÃ§a-las com exito.</p>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-5\">\r\n");
      out.write("            <img  class=\"img-responsive chatbot2\" src=\"image/gifEnois.gif\" alt=\"\">\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"tudoEquipe\" id=\"equipe\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <h1 class=\"subtitulo\">Equipe</h1>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-4 centroEquipe\">\r\n");
      out.write("            <img class=\"imgEquipe\"src=\"image/sergio.jpg\" alt=\"\">\r\n");
      out.write("            <h3 class=\"NomeMembro\">Sergio Ovalle</h3>\r\n");
      out.write("            <p class=\"descricaoMembro\">ResponsÃ¡vel pelo Front-End</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 centroEquipe\">\r\n");
      out.write("            <img class=\"imgEquipe\"src=\"image/piero.jpg\" alt=\"\">\r\n");
      out.write("            <h3 class=\"NomeMembro\">Piero Barbosa</h3>\r\n");
      out.write("            <p class=\"descricaoMembro\">ResponsÃ¡vel pelo ChatBot</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 centroEquipe\">\r\n");
      out.write("            <img class=\"imgEquipe\" src=\"image/thiago.jpg\" alt=\"\">\r\n");
      out.write("            <h3 class=\"NomeMembro\">Thiago Almeida</h3>\r\n");
      out.write("            <p class=\"descricaoMembro\">ResponsÃ¡vel pelo ChatBot</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br><br><br>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-4 centroEquipe\">\r\n");
      out.write("            <img class=\"imgEquipe\" src=\"image/leandro.jpg\" alt=\"\">\r\n");
      out.write("            <h3 class=\"NomeMembro\">Leandro</h3>\r\n");
      out.write("            <p class=\"descricaoMembro\">ResponsÃ¡vel pela documentaÃ§Ã£o</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 centroEquipe\">\r\n");
      out.write("            <img class=\"imgEquipe\"src=\"image/ricardo.jfif\" alt=\"\">\r\n");
      out.write("            <h3 class=\"NomeMembro\">Ricardo</h3>\r\n");
      out.write("            <p class=\"descricaoMembro\">ResponsÃ¡vel pelo Banco de Dados</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-4 centroEquipe\">\r\n");
      out.write("            <img class=\"imgEquipe\"src=\"image/talles.jfif\" alt=\"\">\r\n");
      out.write("            <h3 class=\"NomeMembro\">Talles</h3>\r\n");
      out.write("            <p class=\"descricaoMembro\">ResponsÃ¡vel pelo Back-End</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"tipoContainer\" id=\"contato\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3656.8458839218033!2d-46.62546068544215!3d-23.573977984676706!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce597abf1a28ff%3A0x1b02a58f85e6395e!2sFIAP!5e0!3m2!1spt-BR!2sbr!4v1535462824159\"class=\"mapa\" width=\"100%\" height=\"100%\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-6\">\r\n");
      out.write("            <h1 class=\"subtitulo\">Contato</h1>\r\n");
      out.write("            <p class=\"subtituloContato\">Deixe seu comentario ou sua duvida</p>\r\n");
      out.write("            <form class=\"\">\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label for=\"InputName\" class=\"labelInput\">Digite seu nome:</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"InputName\" placeholder=\"Seu nome\"> </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                  <label for=\"InputEmail1\" class=\"labelInput\">Digite seu email:</label>\r\n");
      out.write("                  <input type=\"email\" class=\"form-control \" id=\"InputEmail1\" placeholder=\"Seu email\"> </div>\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"Textarea\" class=\"labelInput\">Digite um comentario sobre o que achou de nossa empresa:</label>\r\n");
      out.write("                    <textarea class=\"form-control \" id=\"Textarea\" rows=\"3\" placeholder=\"Seu comentario e/ou duvida\"></textarea>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <button type=\"submit\" class=\"btn btn-secondary\" id=\"btnContato\">Enviar</button>\r\n");
      out.write("                </form>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"containerFooter\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-3\">\r\n");
      out.write("                <h1 class=\"tituloFooter\">FINBOT</h1>\r\n");
      out.write("                <p class=\"textaoFooter\">Nossa plataforma busca ajudar resolver seus problemas financeiros e alcanÃ§ar seus sonhos e metas de forma facil, divertifa, interati sustentÃ¡vel. </p>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-md-3\">\r\n");
      out.write("                <h1 class=\"tituloFooter\">Mapa do Site</h1>\r\n");
      out.write("                <p class=\"textoFooter\">Inicio</p>\r\n");
      out.write("                <p class=\"textoFooter\">SugestÃµes</p>\r\n");
      out.write("                <p class=\"textoFooter\">ChatBot</p>\r\n");
      out.write("                <p class=\"textoFooter\">Identidade</p>\r\n");
      out.write("                <p class=\"textoFooter\">Equipe</p>\r\n");
      out.write("                <p class=\"textoFooter\">Contado</p>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-md-3\">\r\n");
      out.write("                <h1 class=\"tituloFooter\">Contato</h1>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"textoFooter\">Email: finbot.fiap@teste.com</p>\r\n");
      out.write("                <p class=\"textoFooter\">Rua: Lins de Vasconcelos</p>\r\n");
      out.write("                <p class=\"textoFooter\">Telefone:7070-7070</p>\r\n");
      out.write("                <p class=\"textoFooter\">Cidade: SÃ£o Paulo</p>\r\n");
      out.write("                <p class=\"textoFooter\">Bairro: AclimaÃ§Ã£o</p>\r\n");
      out.write("\r\n");
      out.write("                <p class=\"textoFooter\">Numero: 1222</p>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"col-md-3\">\r\n");
      out.write("                <h1 class=\"tituloFooter\">Redes sociais</h1>\r\n");
      out.write("                <p class=\"textoFooter\">Facebook</p>\r\n");
      out.write("                <p class=\"textoFooter\">Instagram</p>\r\n");
      out.write("                <p class=\"textoFooter\">Linkdin</p>\r\n");
      out.write("                <p class=\"textoFooter\">twitter</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery-3.2.1.slim.min.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"js/index.js\"></script>\r\n");
      out.write("        <!-- <script type=\"text/javascript\" src=\"js/jquery-3.3.1.min.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </body>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("      <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("      <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("      \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
